### ISSUE TITLE
'getSignature' undefined

### ISSUE THREAD

**Issue by picatextra** [jyfcrw/botbuilder-wechat-connector#5]
When i received msg from wechat my server crash like this 

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'getSignature' of undefined
 at ......\node_modules\wechat\lib\wechat.js:450:34

**Comment by jyfcrw** [comment]
Do you solve this problem?
If not, please open a new issue, I will close this one, because it's been a year.
