### ISSUE TITLE
Add Audio Recognition for connector

### ISSUE THREAD

**Issue by lijiarui** [jyfcrw/botbuilder-wechat-connector#8]
Hi, thanks for the great repo.

As wechatOA can do STT automatically, so I suggest to add recognition function, it means connector can convert audio to speech automatically if the audio response has the `Recognition` field.

When I say audio `你好哈喽!`, wechat audio response log as follows:

```json
{
    "ToUserName": "gh_87e03c422b73", 
    "FromUserName": "o04vx0YXJGTnPdiXLSu1xZW2Ajuo", 
    "CreateTime": "1513529079", 
    "MsgType": "voice", 
    "MediaId": "9seTBfhw1KmTiaORRo4dPXwULfy4DQnyjcnPPJjjT9gwoqU2WXRTEqfwxV2pRQbZ", 
    "Format": "amr", 
    "MsgId": "6500557895850000384", 
    "Recognition": "你好哈喽！"
}
```

I found your code 
```js
if (msgType == 'text') {
  msg = msg.text(wechatMessage.Content);
} else {
  msg = msg.text('');
}
```

I suggest to add `msgType === 'voice'` like this
```js
if (msgType == 'text') {
  msg = msg.text(wechatMessage.Content);
} else if (msgType == 'voice') {
  msg = msg.text(wechatMessage.Recognition);
} else{
  msg = msg.text('');
}
```
Do you have any suggestion to do this? Or if you give some suggestion, I'd like to pull request.

**Comment by jyfcrw** [comment]
OK, merged, thanks.
